//! Compile the release signing keys into whatever links this crate (ADR-0017).
//!
//! **Into the binary, not onto the host.** A key on disk is worth what the
//! path is worth: inside a daemon's state directory it is writable by the
//! process it exists to constrain, and anywhere else it is a file that arrived
//! over the same channel as the binary it verifies. Compiling it in makes the
//! trust descend from the install that put this file here, and makes each
//! version carry the key set for the next one.
//!
//! A **set**, which is the whole rotation mechanism: version *N* is signed by
//! the old key and trusts `{old, new}`, version *N+1* is signed by the new key
//! and trusts `{new}`. Two ordinary upgrades retire a key, so a leak is
//! answered by a release rather than by visiting every machine in the fleet.
//!
//! **An empty set is a legitimate build and is the default.** A binary with no
//! keys refuses every release and says so in those words. That is what anyone
//! building from a checkout gets, and it is the right thing to get: this
//! repository holds no private key, and a placeholder public key would be a
//! build that looks capable of verifying and is not.
//!
//! This used to live in `agent/build.rs` and was moved here whole when
//! ADR-0018 gave the Controller's updater the same contract. There is one key
//! set in the tree, generated once, and the agent and the manager link the
//! same constant -- which is what stops a rotation that lands on one component
//! and not the other.

use std::fmt::Write as _;
use std::path::{Path, PathBuf};

fn main() {
    let manifest = PathBuf::from(env!("CARGO_MANIFEST_DIR"));
    let out = PathBuf::from(std::env::var("OUT_DIR").expect("cargo sets OUT_DIR"));
    // `agent/keys`, from `agent/release`. Deliberately *not* copied into this
    // crate: `scripts/check-release-keys.sh` compares that directory against
    // the installer's PEM copy, and a second location for the same key is a
    // second place a rotation can be applied to and forgotten.
    signing_keys(&manifest.join("..").join("keys"), &out.join("signing_keys.rs"));
}

fn signing_keys(dir: &Path, out: &Path) {
    println!("cargo:rerun-if-changed={}", dir.display());
    println!("cargo:rerun-if-env-changed=BYSTACK_SIGNING_KEYS");

    let mut keys: Vec<[u8; 32]> = Vec::new();
    let mut sources: Vec<String> = Vec::new();

    // Files first, so a checkout's committed keys are the baseline and the
    // environment adds to them rather than being an alternative spelling
    // somebody has to remember to keep in step.
    if let Ok(entries) = std::fs::read_dir(dir) {
        let mut paths: Vec<PathBuf> = entries
            .flatten()
            .map(|entry| entry.path())
            .filter(|path| path.extension().is_some_and(|e| e == "pub"))
            .collect();
        // Sorted, so the generated file is identical on every machine. An
        // unsorted directory read would make the build non-reproducible for
        // no reason anyone would ever find.
        paths.sort();
        for path in paths {
            let text = std::fs::read_to_string(&path)
                .unwrap_or_else(|e| panic!("cannot read {}: {e}", path.display()));
            for key in parse(&text, &path.display().to_string()) {
                keys.push(key);
            }
            sources.push(path.display().to_string());
        }
    }

    if let Ok(value) = std::env::var("BYSTACK_SIGNING_KEYS") {
        for key in parse(&value.replace([',', ':', ';'], "\n"), "BYSTACK_SIGNING_KEYS") {
            keys.push(key);
        }
        sources.push("BYSTACK_SIGNING_KEYS".into());
    }

    keys.dedup();

    let mut rust = String::from(
        "// Generated by build.rs. The keys this build will accept a release from.\n\
         pub const SIGNING_KEYS: &[[u8; 32]] = &[\n",
    );
    for key in &keys {
        let bytes: Vec<String> = key.iter().map(|b| format!("0x{b:02x}")).collect();
        let _ = writeln!(rust, "    [{}],", bytes.join(", "));
    }
    rust.push_str("];\n");

    std::fs::write(out, rust).expect("cannot write the generated key set");

    // Printed rather than silent, because "which keys is this binary willing
    // to trust" is the one property of a build that cannot be recovered by
    // looking at the output afterwards.
    if keys.is_empty() {
        println!("cargo:warning=no release signing keys; nothing built from this tree can verify an upgrade (agent/keys/README.md)");
    } else {
        println!(
            "cargo:warning=built trusting {} release signing key(s) from {}",
            keys.len(),
            sources.join(", ")
        );
    }
}

/// Hex, one key per line, `#` comments and blank lines ignored.
///
/// Refuses anything that is not exactly 32 bytes rather than skipping it. A
/// mistyped key that is silently dropped is a release nobody can install, and
/// the failure would surface on a fleet rather than on the machine that built
/// the binary.
fn parse(text: &str, source: &str) -> Vec<[u8; 32]> {
    let mut keys = Vec::new();
    for (number, line) in text.lines().enumerate() {
        let line = line.split('#').next().unwrap_or("").trim();
        if line.is_empty() {
            continue;
        }
        let at = format!("{source}:{}", number + 1);
        assert!(
            line.len() == 64,
            "{at}: an ed25519 public key is 64 hex characters, got {}",
            line.len()
        );
        let mut key = [0u8; 32];
        for (index, byte) in key.iter_mut().enumerate() {
            *byte = u8::from_str_radix(&line[index * 2..index * 2 + 2], 16)
                .unwrap_or_else(|_| panic!("{at}: not hexadecimal"));
        }
        keys.push(key);
    }
    keys
}
