//! Generate the wire types from the checked-in descriptor set, and compile in
//! the keys that decide which binaries this agent will run.
//!
//! `prost-build` normally shells out to `protoc`. We feed it a compiled
//! `FileDescriptorSet` instead, produced by
//! `backend/scripts/generate_proto.py` and committed alongside the `.proto`.
//!
//! The point is that building the agent requires nothing but a Rust
//! toolchain. That is worth more here than anywhere else in the project: the
//! agent is the component cross-compiled for every architecture in a fleet,
//! and a `protoc` dependency would have to be satisfied in each of those
//! toolchains — including the ones running in whatever CI a contributor has.

use std::fmt::Write as _;
use std::path::{Path, PathBuf};

fn main() {
    let manifest = PathBuf::from(env!("CARGO_MANIFEST_DIR"));
    let out = PathBuf::from(std::env::var("OUT_DIR").expect("cargo sets OUT_DIR"));

    let descriptor = manifest.join("proto/agent.bin");

    // Rerun on the descriptor, not on the `.proto`: the descriptor is what
    // this build actually consumes, and watching the source would silently
    // pass on a schema edit that was never regenerated.
    println!("cargo:rerun-if-changed={}", descriptor.display());

    let mut config = prost_build::Config::new();
    config.skip_protoc_run();
    config.file_descriptor_set_path(&descriptor);
    config
        .compile_protos(&["bystack/agent/v1/agent.proto"], &["."])
        .expect("failed to generate wire types from proto/agent.bin");

    signing_keys(&manifest.join("keys"), &out.join("signing_keys.rs"));
}

/// Compile the release signing keys into the binary (ADR-0017).
///
/// **Into the binary, not onto the host.** A key on disk is worth what the
/// path is worth: inside the daemon's `StateDirectory` it is writable by the
/// process it exists to constrain, and anywhere else it is a file that arrived
/// over the same channel as the binary it verifies. Compiling it in makes the
/// trust descend from the install that put this file here, and makes each
/// version carry the key set for the next one.
///
/// A **set**, which is the whole rotation mechanism: version *N* is signed by
/// the old key and trusts `{old, new}`, version *N+1* is signed by the new key
/// and trusts `{new}`. Two ordinary upgrades retire a key, so a leak is
/// answered by a release rather than by visiting every machine in the fleet.
///
/// **An empty set is a legitimate build and is the default.** An agent with no
/// keys does not advertise the `upgrade` capability, so a Controller refuses to
/// start a transfer to it with a sentence instead of sending two megabytes to
/// a host that was always going to refuse them. That is what anyone building
/// from a checkout gets, and it is the right thing to get: this repository
/// holds no private key, and a placeholder public key would be a build that
/// looks capable of verifying and is not.
fn signing_keys(dir: &Path, out: &Path) {
    println!("cargo:rerun-if-changed={}", dir.display());
    println!("cargo:rerun-if-env-changed=BYSTACK_SIGNING_KEYS");

    let mut keys: Vec<[u8; 32]> = Vec::new();
    let mut sources: Vec<String> = Vec::new();

    // Files first, so a checkout's committed keys are the baseline and the
    // environment adds to them rather than being an alternative spelling
    // somebody has to remember to keep in step.
    if let Ok(entries) = std::fs::read_dir(dir) {
        let mut paths: Vec<PathBuf> = entries
            .flatten()
            .map(|entry| entry.path())
            .filter(|path| path.extension().is_some_and(|e| e == "pub"))
            .collect();
        // Sorted, so the generated file is identical on every machine. An
        // unsorted directory read would make the build non-reproducible for
        // no reason anyone would ever find.
        paths.sort();
        for path in paths {
            let text = std::fs::read_to_string(&path)
                .unwrap_or_else(|e| panic!("cannot read {}: {e}", path.display()));
            for key in parse(&text, &path.display().to_string()) {
                keys.push(key);
            }
            sources.push(path.display().to_string());
        }
    }

    if let Ok(value) = std::env::var("BYSTACK_SIGNING_KEYS") {
        for key in parse(&value.replace([',', ':', ';'], "\n"), "BYSTACK_SIGNING_KEYS") {
            keys.push(key);
        }
        sources.push("BYSTACK_SIGNING_KEYS".into());
    }

    keys.dedup();

    let mut rust = String::from(
        "// Generated by build.rs. The keys this agent will accept a release from.\n\
         pub const SIGNING_KEYS: &[[u8; 32]] = &[\n",
    );
    for key in &keys {
        let bytes: Vec<String> = key.iter().map(|b| format!("0x{b:02x}")).collect();
        let _ = writeln!(rust, "    [{}],", bytes.join(", "));
    }
    rust.push_str("];\n");

    std::fs::write(out, rust).expect("cannot write the generated key set");

    // Printed rather than silent, because "which keys is this binary willing
    // to trust" is the one property of a build that cannot be recovered by
    // looking at the output afterwards.
    if keys.is_empty() {
        println!("cargo:warning=no release signing keys; this agent cannot be upgraded over the wire (agent/keys/README.md)");
    } else {
        println!("cargo:warning=agent built trusting {} release signing key(s) from {}", keys.len(), sources.join(", "));
    }
}

/// Hex, one key per line, `#` comments and blank lines ignored.
///
/// Refuses anything that is not exactly 32 bytes rather than skipping it. A
/// mistyped key that is silently dropped is a release nobody can install, and
/// the failure would surface on a fleet rather than on the machine that built
/// the binary.
fn parse(text: &str, source: &str) -> Vec<[u8; 32]> {
    let mut keys = Vec::new();
    for (number, line) in text.lines().enumerate() {
        let line = line.split('#').next().unwrap_or("").trim();
        if line.is_empty() {
            continue;
        }
        let at = format!("{source}:{}", number + 1);
        assert!(
            line.len() == 64,
            "{at}: an ed25519 public key is 64 hex characters, got {}",
            line.len()
        );
        let mut key = [0u8; 32];
        for (index, byte) in key.iter_mut().enumerate() {
            *byte = u8::from_str_radix(&line[index * 2..index * 2 + 2], 16)
                .unwrap_or_else(|_| panic!("{at}: not hexadecimal"));
        }
        keys.push(key);
    }
    keys
}
